services:
  analytics:
    networks:
      - financer-services_database
    external_links:
      - financer-services-postgres-1:postgres
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    ports:
      - "1234:1234"
    env_file:
      - stack.env
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:1234/healthcheck > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  financer-services_database:
    external: true

volumes:
  go-mod-cache: 