FROM golang:1.23.4

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY .air.toml ./

COPY . .

EXPOSE 1234

ENV GOFLAGS="-buildvcs=false"
CMD ["air", "-c", ".air.toml"] 